baseurl: "https://example.org/"
title: "Blog Test Hugo"
theme: "hugo-nederburg-theme"
languageCode: "en-us"
# Enable comments by entering your Disqus shortname
disqusShortname: ""
# Enable Google Analytics by entering your tracking code
googleAnalytics: ""
preserveTaxonomyNames: true
paginate: 5 #frontpage pagination

Params:
  slogan: "A fast &amp; secure theme"
  description: "Describe your website" # meta description
  author: "Göran Svensson"
  authorLink: "https://appernetic.io/"
  # bio: "blablabla"
  # copyright: "&copy; 2018 Göran Svensson, Nederburg Hugo Theme by nawnaw. A port of Tracks by Compete Themes."
  email: "nawnaw"
  # social:
  #   - facebook     : "full profile url in facebook"
  #     googleplus   : "full profile url in googleplus"
  #     email        : "email@example.com"
  #     twitter      : "full profile url in twitter"
  #     linkedin     : "full profile url in linkedin"
  #     stackoverflow: "full profile url in stackoverflow"
  #     instagram    : "full profile url in instagram"
  #     github       : "full profile url in github"
  #     pinterest    : "full profile url in pinterest"
  #     rss          : true